name: Auto AMD64 Build

on:
  push:
    branches: [ master, develop ]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

env:
  ALIYUN_REGION: cn-hangzhou
  AMD64_ZONES: cn-hangzhou-j,cn-hangzhou-k,cn-hangzhou-b,cn-hangzhou-g,cn-hangzhou-h,cn-hangzhou-i
  RUNNER_NAME: openresty-amd64-spot

jobs:
  find-cheapest:
    runs-on: ubuntu-latest
    outputs:
      cheapest_instance: ${{ steps.find_cheapest.outputs.cheapest_instance }}
      cheapest_zone: ${{ steps.find_cheapest.outputs.cheapest_zone }}
      spot_price_limit: ${{ steps.find_cheapest.outputs.spot_price_limit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Aliyun CLI
        run: |
          chmod +x .github/scripts/configure-aliyun-cli.sh
          .github/scripts/configure-aliyun-cli.sh \
            "${{ env.ALIYUN_REGION }}" \
            "${{ secrets.ALIYUN_ACCESS_KEY_ID }}" \
            "${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}"

      - name: Find Cheapest Instance
        id: find_cheapest
        env:
          ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        run: |
          python3 .github/scripts/find-cheapest-instance.py \
            "${{ env.ALIYUN_REGION }}" \
            "" \
            "8" "8" "8" "8"

  create-spot-runner:
    needs: find-cheapest
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    outputs:
      instance_id: ${{ steps.create_instance.outputs.instance_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Aliyun CLI
        run: |
          chmod +x .github/scripts/configure-aliyun-cli.sh
          .github/scripts/configure-aliyun-cli.sh \
            "${{ env.ALIYUN_REGION }}" \
            "${{ secrets.ALIYUN_ACCESS_KEY_ID }}" \
            "${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}"

      - name: Get Runner Registration Token
        id: get_token
        run: |
          chmod +x .github/scripts/get-runner-registration-token.py
          echo "Fetching registration token..."
          # Use Personal Access Token (PAT) - required for runner registration
          # Note: Secret names cannot start with GITHUB_
          # Please create a secret named RUNNER_REGISTRATION_PAT with a PAT that has 'repo' scope
          if [ -z "${{ secrets.RUNNER_REGISTRATION_PAT }}" ]; then
            echo "❌ RUNNER_REGISTRATION_PAT secret is not set"
            echo "Please create a Personal Access Token with 'repo' scope and add it as a secret named RUNNER_REGISTRATION_PAT"
            echo "See: .github/scripts/TROUBLESHOOTING-registration-token.md for details"
            exit 1
          fi
          echo "✓ Using Personal Access Token from RUNNER_REGISTRATION_PAT secret"
          # Run script - stderr will show logs, stdout will have token if successful
          set +e
          REGISTRATION_TOKEN=$(python3 .github/scripts/get-runner-registration-token.py \
            "${{ secrets.RUNNER_REGISTRATION_PAT }}" \
            "dianplus" \
            "openresty" 2>&1)
          EXIT_CODE=$?
          set -e
          
          if [ $EXIT_CODE -ne 0 ]; then
            echo "❌ Failed to get registration token (exit code: $EXIT_CODE)"
            echo "Output:"
            echo "$REGISTRATION_TOKEN"
            exit 1
          fi
          
          # Extract token (should be the last line if script succeeded)
          TOKEN=$(echo "$REGISTRATION_TOKEN" | tail -1)
          
          if [ -z "$TOKEN" ] || [ "$TOKEN" = "" ]; then
            echo "❌ Registration token is empty"
            echo "Full output:"
            echo "$REGISTRATION_TOKEN"
            exit 1
          fi
          
          echo "registration_token=$TOKEN" >> $GITHUB_OUTPUT
          echo "✓ Registration token obtained (hidden for security)"

      - name: Create Spot Instance
        id: create_instance
        env:
          ALIYUN_VSWITCH_ID_B: ${{ secrets.ALIYUN_VSWITCH_ID_B }}
          ALIYUN_VSWITCH_ID_G: ${{ secrets.ALIYUN_VSWITCH_ID_G }}
          ALIYUN_VSWITCH_ID_H: ${{ secrets.ALIYUN_VSWITCH_ID_H }}
          ALIYUN_VSWITCH_ID_I: ${{ secrets.ALIYUN_VSWITCH_ID_I }}
          ALIYUN_VSWITCH_ID_J: ${{ secrets.ALIYUN_VSWITCH_ID_J }}
          ALIYUN_VSWITCH_ID_K: ${{ secrets.ALIYUN_VSWITCH_ID_K }}
          ALIYUN_VSWITCH_ID: ${{ secrets.ALIYUN_VSWITCH_ID }}
        run: |
          python3 .github/scripts/create-spot-instance.py \
            "${{ needs.find-cheapest.outputs.cheapest_instance }}" \
            "${{ needs.find-cheapest.outputs.cheapest_zone }}" \
            "${{ needs.find-cheapest.outputs.spot_price_limit }}" \
            "${{ secrets.ALIYUN_AMD64_IMAGE_ID }}" \
            "${{ secrets.ALIYUN_SECURITY_GROUP_ID }}" \
            "${{ secrets.ALIYUN_VSWITCH_ID }}" \
            "${{ secrets.ALIYUN_KEY_PAIR_NAME }}" \
            "${{ steps.get_token.outputs.registration_token }}" \
            "${{ env.RUNNER_NAME }}" \
            "x64"

      - name: Wait for Instance Ready
        run: |
          python3 .github/scripts/wait-instance-ready.py \
            "${{ steps.create_instance.outputs.instance_id }}" \
            "600"

      - name: Check Runner Status
        if: steps.create_instance.outputs.instance_id != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 .github/scripts/check-runner-status.py \
            "${{ steps.create_instance.outputs.instance_id }}"
          
      - name: Wait for Runner Registration
        if: steps.create_instance.outputs.instance_id != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Waiting for runner to register and become available..."
          INSTANCE_NAME="${{ env.RUNNER_NAME }}-$(date +%s)"
          MAX_WAIT=300
          SLEEP_INTERVAL=10
          ELAPSED=0
          
          while [ $ELAPSED -lt $MAX_WAIT ]; do
            API_RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/dianplus/openresty/actions/runners")
            
            # Check if API response is valid and has runners array
            if echo "$API_RESPONSE" | jq -e '.runners' > /dev/null 2>&1; then
              RUNNER_STATUS=$(echo "$API_RESPONSE" | \
                jq -r --arg prefix "${{ env.RUNNER_NAME }}" \
                '.runners[]? | select(.name | startswith($prefix)) | .status' | head -1)
              
              if [ -n "$RUNNER_STATUS" ] && [ "$RUNNER_STATUS" != "null" ]; then
                if [ "$RUNNER_STATUS" = "online" ]; then
                  echo "✅ Runner is online and ready"
                  break
                elif [ "$RUNNER_STATUS" = "offline" ]; then
                  echo "⏳ Runner is registered but offline (elapsed: ${ELAPSED}s)"
                else
                  echo "⏳ Runner status: $RUNNER_STATUS (elapsed: ${ELAPSED}s)"
                fi
              else
                echo "⏳ Waiting for runner registration... (elapsed: ${ELAPSED}s)"
              fi
            else
              echo "⏳ Waiting for runner registration... (API response may be empty, elapsed: ${ELAPSED}s)"
            fi
            
            sleep $SLEEP_INTERVAL
            ELAPSED=$((ELAPSED + SLEEP_INTERVAL))
          done
          
          if [ "$RUNNER_STATUS" != "online" ]; then
            echo "⚠️ Runner may not be ready yet, but proceeding with build job"
            echo "Build job will wait for runner to become available"
          fi

  build-amd64:
    needs: create-spot-runner
    runs-on: [self-hosted, linux, AMD64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t openresty:latest .
          docker tag openresty:latest openresty:amd64-$(date +%Y%m%d-%H%M%S)

  cleanup:
    needs: [create-spot-runner, build-amd64]
    runs-on: ubuntu-latest
    # Only cleanup if build job completed (success or failure), not if it was skipped
    if: always() && (needs.build-amd64.result == 'success' || needs.build-amd64.result == 'failure')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Aliyun CLI
        if: needs.create-spot-runner.outputs.instance_id != ''
        run: |
          chmod +x .github/scripts/configure-aliyun-cli.sh
          .github/scripts/configure-aliyun-cli.sh \
            "${{ env.ALIYUN_REGION }}" \
            "${{ secrets.ALIYUN_ACCESS_KEY_ID }}" \
            "${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}"

      - name: Cleanup Spot Instance
        if: needs.create-spot-runner.outputs.instance_id != ''
        run: |
          echo "Cleaning up instance: ${{ needs.create-spot-runner.outputs.instance_id }}"
          echo "Build job result: ${{ needs.build-amd64.result }}"
          python3 .github/scripts/cleanup-instance.py \
            "${{ needs.create-spot-runner.outputs.instance_id }}" \
            "true"
          echo "✅ Instance cleaned up successfully"
